# Generated by Django 2.1.5 on 2019-01-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.IntegerField()),
                ('close', models.IntegerField()),
                ('low', models.IntegerField()),
                ('hight', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
