# Generated by Django 2.1.5 on 2019-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='hight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='volume',
            field=models.FloatField(),
        ),
    ]
